development:
  adapter: postgresql
  encoding: utf8
  database: depot_dev_postgresql
  pool: 5
  username: Marlo
  password: secret
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: depot_test_postgresql
  pool: 5
  username: Marlo
  password: secret
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: depot_prod_postgresql
  pool: 5
  username: Marlo
  password: secret
  timeout: 5000
  host: localhost
  